apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: cracker786/voting-app
        ports:
        - containerPort: 80
          name: vote
        env:
        - name: OPTION_A
          value: Cats
        - name: OPTION_B
          value: Dogs